vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /assets/ILLUSTRATIONS
            upload_destination: '%kernel.project_dir%/public/assets/ILLUSTRATIONS'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
